Ext.define('BGRM.store.BlastingTaskDetail', {
	extend : 'Ext.data.Store',
	requires : 'BGRM.model.BlastingTaskDetail',
	model : 'BGRM.model.BlastingTaskDetail',
	data : [{
		row : '2',
		holeNo : '3',
		holeDepth:'27.8',
		blockPosition:'24',
		sand : '0.5',
		sandHeight : '26',
		ten:'1',
		five:'2',
		detonatorstage : '10',
		powderHeight : '21',
		sand2:'1.5',
		finalSandHeight:'',
		finalHoleDepth : '8',
		blastingHeight : ''
	},{
		row : '2',
		holeNo : '5',
		holeDepth:'27.8',
		blockPosition:'24',
		sand : '0.5',
		sandHeight : '26',
		ten:'1',
		five:'2',
		detonatorstage : '10',
		powderHeight : '21',
		sand2:'1.5',
		finalSandHeight:'',
		finalHoleDepth : '8',
		blastingHeight : ''
	}, {
		row : '2',
		holeNo : '7',
		holeDepth:'27.8',
		blockPosition:'24',
		sand : '0.5',
		sandHeight : '27',
		ten:'3',
		five:'2',
		detonatorstage : '10',
		powderHeight : '21',
		sand2:'1.5',
		finalSandHeight:'',
		finalHoleDepth : '7',
		blastingHeight : ''
	},{
		row : '2',
		holeNo : '9',
		holeDepth:'27.8',
		blockPosition:'24',
		sand : '0.5',
		sandHeight : '26',
		ten:'1',
		five:'2',
		detonatorstage : '10',
		powderHeight : '21',
		sand2:'1.5',
		finalSandHeight:'',
		finalHoleDepth : '8',
		blastingHeight : ''
	}]
});